import type { ThemeConfig } from "antd";
import { COLORS } from "../../tailwind.config";

export const theme: ThemeConfig = {
  token: {
    colorPrimary: COLORS.primary.DEFAULT,
    colorBgLayout: "#fff",
    fontFamily: "Figtree, sans-serif",
    colorSuccess: COLORS.success.DEFAULT,
    colorSuccessHover: COLORS.success.hover,
    colorError: COLORS.error.DEFAULT,
    colorErrorHover: COLORS.error.hover,
    colorWarning: COLORS.warning.DEFAULT,
    colorWarningHover: COLORS.warning.hover,
  },
  components: {
    Button: {
      colorPrimaryBg: COLORS.primary.DEFAULT,
      colorPrimaryBgHover: COLORS.primary.hover,
      borderRadius: 6,
      borderRadiusLG: 6,
      borderRadiusSM: 6,
      borderRadiusXS: 6,
      fontWeight: 500,
      boxShadow: "0 0",
      paddingInline: 20.5,
      paddingInlineLG: 20.5,
      paddingInlineSM: 20.5,
      fontSizeXL: 16,
      fontSizeLG: 16,
      fontSizeSM: 14,
      fontSize: 14,
      controlHeightLG: 48,
      controlHeight: 42,
      controlHeightSM: 36,
      controlHeightXS: 29,
    },
    Input: {
      activeBorderColor: COLORS.primary.DEFAULT,
      colorErrorBorder: COLORS.error.DEFAULT,
      colorWarningBorder: COLORS.warning.DEFAULT,
      colorBorder: COLORS.black.border,
      borderRadiusLG: 6,
      borderRadius: 6,
      borderRadiusSM: 6,
      fontSizeLG: 16,
      fontSize: 14,
      fontSizeSM: 14,
      paddingBlockLG: 11.5,
      paddingInlineLG: 11,
      paddingBlock: 15.5,
      paddingInline: 12,
      paddingBlockSM: 3,
      paddingInlineSM: 7,
      lineHeight: 1,
    },
    Typography: {
      fontSizeHeading1: 30,
      fontSizeHeading2: 24,
      fontSizeHeading3: 22,
      fontSizeHeading4: 20,
      fontSizeHeading5: 18,
      lineHeightHeading1: 38 / 30,
      lineHeightHeading2: 30 / 24,
      lineHeightHeading3: 27 / 22,
      lineHeightHeading4: 24 / 20,
      lineHeightHeading5: 22 / 18,
    },
    Divider: {
      verticalMarginInline: 0,
    },
    Badge: {
      colorSuccess: COLORS.success.DEFAULT,
      colorSuccessHover: COLORS.success.hover,
      colorError: COLORS.error.DEFAULT,
      colorErrorHover: COLORS.error.hover,
      colorWarning: COLORS.warning.DEFAULT,
      colorWarningHover: COLORS.warning.hover,
    },
    DatePicker: {
      activeBorderColor: COLORS.primary.DEFAULT,
      colorErrorBorder: COLORS.error.DEFAULT,
      colorWarningBorder: COLORS.warning.DEFAULT,
      borderRadiusLG: 6,
      borderRadius: 6,
      borderRadiusSM: 6,
      fontSizeLG: 16,
      fontSize: 14,
      fontSizeSM: 14,
      paddingBlockLG: 11.5,
      paddingInlineLG: 11,
      paddingBlock: 15.5,
      paddingInline: 12,
      paddingBlockSM: 3,
      paddingInlineSM: 7,
      lineHeight: 1,
      controlHeight: 48,
      controlHeightLG: 49,
      controlHeightSM: 30,
    },
    Select: {
      activeBorderColor: COLORS.primary.DEFAULT,
      colorErrorBorder: COLORS.error.DEFAULT,
      colorWarningBorder: COLORS.warning.DEFAULT,
      borderRadiusLG: 6,
      borderRadius: 6,
      borderRadiusSM: 6,
      fontSizeLG: 16,
      fontSize: 14,
      fontSizeSM: 14,
      controlHeight: 48,
      controlHeightLG: 49,
      controlHeightSM: 30,
    },
    Table: {
      headerBg: COLORS.secondary[950],
      headerColor: "#fff",
      headerBorderRadius: 12,
      fontSizeHeading1: 600,
      headerSortHoverBg: COLORS.secondary[900],
      bodySortBg: "transparent",
      headerSortActiveBg: COLORS.secondary[900],
      cellPaddingBlock: 12,
      cellPaddingInline: 12,
      rowSelectedBg: "#EEEEF0",
    },
  },
};
