version: '3.8'

services:
  frontend:
    build:
      context: ./dashboard  # Path to your frontend folder
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Exposes the frontend service on port 3001
    depends_on:
      - backend
    environment:
      - APP_ENV=staging
      - NODE_ENV=development
      - NEXT_PUBLIC_BASE_URL=http://localhost:4000  # Use backend service as alias
      - BASE_URL=http://backend:4000  # Use backend service as alias
      - NEXTAUTH_SECRET=generated123
      - NEXTAUTH_URL=http://localhost:3000  # Use frontend service as alias
    networks:
      - superbank-network

  backend:
    build:
      context: ./backend-service  # Path to your backend folder
      dockerfile: Dockerfile
    ports:
      - "4000:4000"  # Exposes the backend service on port 3000
    networks:
      - superbank-network

networks:
  superbank-network:
    driver: bridge
